### ISSUE TITLE
[📚] Can't we use local advanced adverts?  

### ISSUE THREAD

**Issue by yemreeke** [invertase/react-native-google-mobile-ads#519] opened 2024-01-04 08:01 UTC
### Documentation Feedback

Hello,
I am using some ads in my application, which I developed with React Native. These include banner and rewarded ads. In my app, there are posts, and I want to insert an ad between 2 or 3 posts, like nourishing ads. It shouldn't stay at the bottom like a banner; it should appear between the posts.
The ads will load as the user navigates through the posts.
I learned that local advanced ads are placed between such post intervals.
Does the library allow us to use local advanced ads?

<img src="https://github.com/invertase/react-native-google-mobile-ads/assets/47570969/35a74d38-547e-4df0-aa7c-4fa17c4a3007"  height="450" />
<img src="https://github.com/invertase/react-native-google-mobile-ads/assets/47570969/8ffc51bf-2aaa-4e8f-8c97-c196f903178b"  height="450" />

**Comment by dylancom** [comment] 2024-01-05 09:20
I think you mean Native Advanced ads, which can be included with this library: https://github.com/ammarahm-ed/react-native-admob-native-ads.
This issue is a duplicate of: #42

**Closed by dylancom** 2024-01-05 09:20 UTC
Labels: help wanted

**Comment by dylancom** [comment] 2024-12-30 20:57
Native ads are supported as of today! https://docs.page/invertase/react-native-google-mobile-ads/native-ads
