### ISSUE TITLE
[📚] Can this library be installed using npm?

### ISSUE THREAD

**Issue by wetzelschultz** [invertase/react-native-google-mobile-ads#166] opened 2022-06-12 02:17 UTC
Other than using yarn to install, I am wondering if I can use npm to install this library?

**Comment by mikehardy** [comment] 2022-06-12 02:55
Should work. How did it go when you tried it?

**Comment by wetzelschultz** [comment] 2022-06-13 02:47
Not working for me. I am trying the banner ads in the documentation here:
https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads#banner-ads-component 

![Screenshot_1655088273](https://user-images.githubusercontent.com/61079717/173270341-ea6d2ca8-ca17-4df2-8be3-28330fb1039a.png)

**Comment by wetzelschultz** [comment] 2022-06-13 02:47
Not working for me. I am trying the banner ads in the documentation here:
https://docs.page/invertase/react-native-google-mobile-ads/displaying-ads#banner-ads-component 

![Screenshot_1655088273](https://user-images.githubusercontent.com/61079717/173270341-ea6d2ca8-ca17-4df2-8be3-28330fb1039a.png)

**Comment by wetzelschultz** [comment] 2022-06-13 02:48
Sorry, I accidentally clicked the wrong button in Github and closed this issue.

**Comment by mikehardy** [comment] 2022-06-13 14:39
I do exactly this and cannot reproduce

```bash
npx react-native init rngma166repro --npm
cd rngma166repro
npm add react-native-google-mobile-ads
<edit app.json so it has the right stuff, I copied from https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/RNGoogleMobileAdsExample/app.json#L4-L9>
<replace with App.js I show below>
npm run start
npm run android
```

It works. 

```
mike@bistromath:~/work/react-random % npm --version
8.5.5
mike@bistromath:~/work/react-random % node --version
v16.14.2
```

Contents of App.js

```javascript
import React from 'react';
import { BannerAd, BannerAdSize, TestIds } from 'react-native-google-mobile-ads';

const adUnitId = TestIds.BANNER;

function App() {
  return (
    <BannerAd
      unitId={adUnitId}
      size={BannerAdSize.FULL_BANNER}
      requestOptions={{
        requestNonPersonalizedAdsOnly: true,
      }}
    />
  );
}

export default App;
```

![image](https://user-images.githubusercontent.com/782704/173378901-38d46cfa-d8c4-4271-a184-f8c7a168c207.png)


Closing this as not actionable, full reproduction details included in this comment, bug not evident.

**Closed by mikehardy** 2022-06-13 14:39 UTC
Labels: help wanted

**Comment by wjaykim** [comment] 2022-06-14 09:50
If you didn't, try `yarn start --reset-cache`.

**Comment by mikehardy** [comment] 2022-06-14 11:20
Run my exact steps, all of them please

**Comment by wetzelschultz** [comment] 2022-06-14 14:45
> Run my exact steps, all of them please
Now it is working. Thank you
