### ISSUE TITLE
[🐛] AdsConsent.getUserChoices(), after accept all options in GDPR message all user choices are always false in __DEV__ mode

### ISSUE THREAD

**Issue by drakulic-goran** [invertase/react-native-google-mobile-ads#484] opened 2023-11-14 07:31 UTC
### What happened?

I get this warning when I call AdsConsent.getUserChoices(): “Failed to decode tcString ...”.
Ok, I understand that warning is in __DEV__ mode because of
https://github.com/invertase/react-native-google-mobile-ads/blob/03e18fb414c837588fd652fe424cfc15445fdc93/src/AdsConsent.ts#L103-L117

But, the problem is that after a GDPR message is displayed and I consent to all options, when I call AdsConsent.getUserChoices() all user choices are always false. Why this happening, earlier I do not have this problem, everything worked fine in __DEV__ mode, how to fix this and get user choices that I accepted in consent form?

### Platforms

Android, but have not tested behavior on iOS

### React Native Info

```Shell
System:
  OS: macOS 14.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.68 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.0
    path: ~/.nvm/versions/node/v18.12.0/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.npm-global/bin/yarn
  npm:
    version: 8.19.2
    path: ~/.nvm/versions/node/v18.12.0/bin/npm
  Watchman:
    version: 2023.02.27.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.2
    path: /usr/local/opt/openjdk/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "dependencies": {
    "expo": "^49.0.0",
    "expo-build-properties": "~0.8.3",
    "expo-dev-client": "~2.4.11",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-google-mobile-ads": "^12.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  }
}
```

### app.json

```JSON
{
  "expo": {
    "extra": {
      "eas": {
        "projectId": "..."
      }
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "extraProguardRules": "-keep class com.google.android.gms.internal.consent_sdk.** { *; }"
          }
        }
      ]
    ]
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "...",
    "ios_app_id": "...",
    "delay_app_measurement_init": true,
    "user_tracking_usage_description": "Identyfikator ten będzie używany do dostarczania Ci spersonalizowanych reklam."
  }
}
```

**Comment by LagoonProject** [comment] 2023-11-14 09:20
I have the same problem I get warning `Failed to decode tcString ... : [TypeError: Cannot convert undefined value to object]`,
when trying to show `await AdsConsent.getUserChoices()` or `await AdsConsent.getTCModel()`.

Then all choices appear as false.

I would appreciate any help.

**Comment by LukasMod** [comment] 2023-11-14 10:53
I have same problem, always `false` for dev/prod on android (emulator/real device) or iOS (simulator). I checked AdsConsent.ts and it looks that even when there is tcString, decode function throw error and return default values from `new TCModel();`

**Comment by drakulic-goran** [comment] 2023-11-14 11:36
Previously AdsConsent.getUserChoices() was correctly returning the user choices even in __DEV__ mode, not all of them were false, I don't know if it's a bug or we  need to do something different with that function?

**Comment by mikehardy** [comment] 2023-11-14 14:24
This is not a use case of mine so I don't have more specific information and I do not have the ability to actually troubleshoot this - sorry - but as a general troubleshooting thing, I'm always curious when something used to work and now does not.

What changed?

Have you tried to revert to older versions of this library to see if it still works now, on a version where it used to work? That could help inform whether our code here has some change that is a regression, or if the android operating system changed somehow. Thinking like that - separating the possible place the problem could be into smaller and smaller parts until the location of issue is identified

**Comment by LukasMod** [comment] 2023-11-14 14:53
I've also tried [example](https://github.com/invertase/react-native-google-mobile-ads/tree/main/RNGoogleMobileAdsExample) and have same behaviour:
`Failed to decode tcString DP1OzUAP1OzUAEsACCENAaEoAAAAAEPgAATAAAAQaQD2F2K2kKFkPCmQWYAQBCijYEAhQAAAAkCBIAAgAU ...` 
and everything from userChoices is false.
The only thing I changed inside example was `android_app_id` and install library with `yarn add react-native-google-mobile-ads`

If the example works for someone, maybe it's something related to the GDPR setting itself?

**Comment by pepijn-motosumo** [comment] 2023-11-14 17:19
We're seeing this in production. From what I can gather Google's User Messaging Platform shows the consent popup and then generates a TC string from the answer. Then react-native-google-mobile-ads passes it to [@iabtcf/core](https://github.com/InteractiveAdvertisingBureau/iabtcf-es) to parse it. That external library then throws an error because it can't parse it. And react-native-google-mobile-ads ignores the exception and returns defaults. Additionally in dev mode the error is logged.

I do not know:

- Why User Messaging Platform generates a seemingly bad TC string.
- Why the IAB TCF library would throw an error on a _good_ TC string.
- Why react-native-google-mobile-ads ignores the error and acts as if no consent was given.

That last part makes this issue hard to deal with in code, because we can't discern between "the user gave no consent" and "an external dependency is doing a weird thing". For our and the user's sake, we really want to be able to discern that.

**Comment by drakulic-goran** [comment] 2023-11-15 07:59
> This is not a use case of mine so I don't have more specific information and I do not have the ability to actually troubleshoot this - sorry - but as a general troubleshooting thing, I'm always curious when something used to work and now does not.
> 
> What changed?
> 
> Have you tried to revert to older versions of this library to see if it still works now, on a version where it used to work? That could help inform whether our code here has some change that is a regression, or if the android operating system changed somehow. Thinking like that - separating the possible place the problem could be into smaller and smaller parts until the location of issue is identified

This is part of package.json for some working example:
{
  "dependencies": {
    "expo": "^46.0.0",
    "expo-dev-client": "~1.3.1",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "^0.69.6",
    "react-native-google-mobile-ads": "^8.1.2"
  }
}

**Comment by LagoonProject** [comment] 2023-11-15 09:42
It looks like the format of the TC string generated by google UMP is somewhat wrong. It starts with "DP1" and should start with "CP1".

I was able to patch react-native-google-mobile-ads using  [patch-package](https://www.npmjs.com/package/patch-package) to get rid of this.

In AdsConsent.ts change the `getUserChoices `method with :

```
  async getUserChoices(): Promise<AdsConsentUserChoices> {
    const tcString = await native.getTCString();

    // fixing tcString
    let fixedTcString = tcString
    
    if (tcString.startsWith("DP1")) {
      fixedTcString = tcString.replace(/^DP1/, "CP1");
    } 

    let tcModel: TCModel;

    try {
      // tcModel = TCString.decode(tcString);
      
      tcModel = TCString.decode(fixedTcString);

    } catch (e) {
      tcModel = new TCModel();

      if (__DEV__) {
        // eslint-disable-next-line no-console
        console.warn(`Failed to decode tcString ${tcString}:`, e);
      }
    }
```

Then apply patch.

This is by no means a long term solution but allows me to move on for now.

**Comment by StCyr** [comment] 2023-11-15 16:22
yep works! 

with expo you need to rebuild your dev-client though

**Comment by mikehardy** [comment] 2023-11-18 01:33
From user `andwun` on upstream ticket https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/429#issuecomment-1816054530:

>  AdMob support now says the issue has been fixed, the invalid consent strings should be automatically invalidated and the affected users will be prompted for consent again.
> So far, I was able to confirm this on one of our sites.

What a relief! Going to close this as it appears to be resolved

**Closed by mikehardy** 2023-11-18 01:33 UTC
Labels: help wanted

**Comment by AmitDigga** [comment] 2024-05-04 15:57
I am still getting this error in iOS simulator in `__DEV__ == true`

``` json
"dependencies": {
    "@react-native-async-storage/async-storage": "1.21.0",
    "@react-native-firebase/analytics": "^19.2.2",
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/crashlytics": "^19.2.2",
    "@react-native-firebase/remote-config": "^19.2.2",
    "@shopify/react-native-skia": "0.1.221",
    "expo": "~50.0.17",
    "expo-av": "~13.10.6",
    "expo-build-properties": "~0.11.1",
    "expo-dev-client": "~3.3.11",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-google-mobile-ads": "^13.2.0",
    "react-native-reanimated": "~3.6.2"
  },
```

Error
```
Failed to decode tcString undefined: [TypeError: Cannot read property 'split' of undefined]
```

Code Snippet
```
        async function startGoogleMobileAdsSDK() {
            // console.log('Can show ads');
            if (isMobileAdsStartCalled) return;
            isMobileAdsStartCalled = true;
            try {
                // (Optional, iOS) Handle Apple's App Tracking Transparency manually.
                const gdprApplies = await AdsConsent.getGdprApplies();
                setIsInEUZone(gdprApplies ? 'yes' : 'no');
                console.log('gdprApplies', gdprApplies)
                const purposeConsents = await AdsConsent.getPurposeConsents();
                const hasConsentForPurposeOne = gdprApplies && purposeConsents.startsWith("1");
                console.log('hasConsentForPurposeOne', hasConsentForPurposeOne)
                const userChoices = await AdsConsent.getUserChoices();
                const canRequestPersonalizedAds = userChoices.selectPersonalisedAds;
                console.log('canRequestPersonalizedAds', canRequestPersonalizedAds)
                console.log('canStoreData', userChoices.storeAndAccessInformationOnDevice)
                // console.log('getUserChoices', await AdsConsent.getUserChoices());
                // const personalizedAds = purposeConsents.startsWith("1");
                await initAndLoadAd(canRequestPersonalizedAds);
            } catch (e) {
                initAndLoadAd(false);
            }

        }
```

Logs:
```
 LOG  gdprApplies false
 LOG  hasConsentForPurposeOne false
 WARN  Failed to decode tcString undefined: [TypeError: Cannot read property 'split' of undefined]
 LOG  canRequestPersonalizedAds false
 LOG  canStoreData false

```

### User Details:
1. User is NOT_EEA, by debug flag
2. User click Allow for ATT


I thought this issues was fixed or allowing ATT, should have returned true.
