### ISSUE TITLE
[🐛] Are Native Ads supported?

### ISSUE THREAD

**Issue by renatomserra** [invertase/react-native-google-mobile-ads#489] opened 2023-11-23 16:36 UTC
### What happened?

Hellow,
Cant find any documentation around it so i feel like the answer is no, but wanted to check.
Are native ads supported?

### Platforms

Android and iOS

### React Native Info

```Shell
n/a
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
n/a
```

### app.json

```JSON
n/a
```

**Comment by mikehardy** [comment] 2023-11-23 17:22
possibly related as I think the term is somewhat ambiguous and may === fluid ? #277

**Comment by renatomserra** [comment] 2023-11-23 17:27
hmm this is what i mean @mikehardy https://admob.google.com/home/resources/native-ads-playbook/
Basically banner ads where we get to customize how they look to make them feel native to the app

**Comment by TaylorDale** [comment] 2023-12-06 00:43
Can we put a bounty on this or something? Would be happy to contribute

**Comment by mikehardy** [comment] 2023-12-06 01:30
Now that I look more closely (thanks for the link @renatomserra ) I think this is a duplicate of the also-not-implemented #42 

The closest that got was me reaching out to an existing implementation that I think worked! It appeared there was some agreement we could merge the repos and get the support here but nothing came of it.

However - the reason I mention that is because for the most part we are professional developers right? (there are quite a few hobbyists in the react-native space which I think is awesome but this is an *ads* module, it's money-related). If we're talking about a bounty, perhaps that could help convince the owner of the other repo to post a PR merging stuff in ? Or could be used to fund someone to do the same ?

I do not personally have the time to do this but I do take maintainership seriously and would collaborate with someone to help get a PR merged and released if anyone was the real motor behind the work to do the PR

With the reference to #42 now that I think I understand the request better I am going to close this as a duplicate but it's not with prejudice or anything. Feel free to continue discussion on 42 - to reach out to the other repo, to propose a PR - anything that would move it forward works for me.

**Closed by mikehardy** 2023-12-06 01:30 UTC
Labels: help wanted

**Comment by renatomserra** [comment] 2024-01-13 22:20
Thanks @mikehardy i've used that repo, its extremely unreliable hence why i want to move out.
I appreciate the explanation, id also be happy to participate in a bounty if it was to be implemented in a well maintained repo like this one.

**Comment by mikehardy** [comment] 2024-01-13 23:54
> Thanks @mikehardy i've used that repo, its extremely unreliable hence why i want to move out.
> I appreciate the explanation, id also be happy to participate in a bounty if it was to be implemented in a well maintained repo like this one.

@birdofpreyru - apologies for just randomly tagging you if it's bothersome but if I understand correctly you have done some work for hire in this repo? I thought you might be interested in this line of thought for that reason. I don't have the extra development time personally but as with the last effort I'm always happy to integrate a well done PR and can make time for that collaboration. Cheers

**Comment by birdofpreyru** [comment] 2024-01-14 12:11
No need for apologies @mikehardy , being a freelance software engineer I am glad when anybody just recalls me in connection to any reasonably paid job I can do. Speaking of which, I believe I can see through the native ads support. Having not looked into it yet, I am not sure how much efforts it will take, and thus what the fair payment would be. Speaking off the top of my head, perhaps it will take a couple of days of dev time, spread across a few weeks. I guess a 750 USD bounty will make it happen :)

**Comment by renatomserra** [comment] 2024-01-17 12:58
awesome, @mikehardy how do we go about setting a bounty that people can contribute to? i have never done that before :D

**Comment by birdofpreyru** [comment] 2024-01-17 15:14
@renatomserra perhaps I can create a https://www.gofundme.com campaign... I have no experience with that platform, but I guess it should suite our purpose here. I also have [GitHub.Sponsors account](https://github.com/sponsors/birdofpreyru), I believe we can use it to collect contributions towards this work; and also I can write regular business invoices, to be paid to my bank account (Spain-based). Sure, I am open for any other good alternative.

**Comment by dylancom** [comment] 2024-01-17 15:36
@birdofpreyru awesome you'd like to take on a bounty for this feature. I believe 750 USD is "very" optimistic though. It's not for nothing that most admob libraries skipped the implementation. There seems to be just 1 dedicated lib that apparently doesn't work well either after years. Would be great to see this integrated.

**Comment by birdofpreyru** [comment] 2024-01-17 15:39
I don't mind at all to aim for a larger number, 1500 USD? :hugs:

**Comment by dylancom** [comment] 2024-12-30 20:57
Native ads are supported as of today! https://docs.page/invertase/react-native-google-mobile-ads/native-ads
