### ISSUE TITLE
Add installation guide for Expo users

### ISSUE THREAD

**Issue by DoneDeal0** [invertase/react-native-google-mobile-ads#155] opened 2022-05-30 17:43 UTC
## Issue

Expo requires its users to use your library, but doesn't provide any installation guide. I've checked [Arekjaar4](https://github.com/Arekjaar4)'s tutorial in #150 , but the build always fail. I think you will soon have plenty of Expo users asking you the same question, so it would definitely worth it to provide an Expo installation tutorial on your website.

Here is what I did:

- `yarn add react-native-google-mobile-ads`
- add adMob keys to `app.json`:
```js
 "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-blabla",
    "ios_app_id": "ca-app-pub-blabla"
  }
```
- add preview field in `eas.json`:
```js
"preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      }
    },
```
- run `expo run:android` (it exposes the android folder)
- run `eas build -p android --profile preview`

The build failed with this error:
```js
// (...)
> Configure project :react-native-google-mobile-ads
33
:react-native-google-mobile-ads package.json found at /home/expo/workingdir/build/node_modules/react-native-google-mobile-ads/package.json
34
:react-native-google-mobile-ads package.json found at /home/expo/workingdir/build/node_modules/react-native-google-mobile-ads/package.json
35
:react-native-google-mobile-ads:version set from package.json: 6.2.5 (6,2,5 - 6002005)
36
:react-native-google-mobile-ads:android.compileSdk using custom value: 30
37
:react-native-google-mobile-ads:android.targetSdk using custom value: 30
38
:react-native-google-mobile-ads:android.minSdk using custom value: 21
39
:react-native-google-mobile-ads:reactNativeAndroidDir /home/expo/workingdir/build/node_modules/react-native/android
40
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
41
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
42
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
43
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
44
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
45
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
46
[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
47
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
48
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
49
[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

// (…)

> Task :react-native-google-mobile-ads:preBuild UP-TO-DATE
108
> Task :react-native-google-mobile-ads:preReleaseBuild UP-TO-DATE
109
> Task :react-native-google-mobile-ads:compileReleaseAidl NO-SOURCE

Task :react-native-google-mobile-ads:packageReleaseRenderscript NO-SOURCE
Task :react-native-google-mobile-ads:writeReleaseAarMetadata

> Task :app:checkReleaseAarMetadata FAILED
166
[stderr] FAILURE: Build failed with an exception.
167
[stderr] * What went wrong:
168
[stderr] Execution failed for task ':app:checkReleaseAarMetadata'.
169
[stderr] > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
170
[stderr]    > The minCompileSdk (31) specified in a
171
[stderr]      dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
172
[stderr]      is greater than this module's compileSdkVersion (android-30).
173
[stderr]      Dependency: androidx.work:work-runtime:2.7.0.
174
[stderr]      AAR metadata file: /home/expo/.gradle/caches/transforms-3/ffee51ff6db99f884b0e8a6a5d65a88b/transformed/work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
175
[stderr] * Try:
176
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

I've also tried to add this in `android/app/src/main/AndroidManifest.xml`:
```js
<meta-data android:name="com.google.android.gms.ads.DELAY_APP_MEASUREMENT_INIT" android:value="false"/>
```

It doesn't work. So a step-by-step tutorial would be useful for a lot of people I guess.

Thank you! (I havn't added a fire emoji in the title, but yes, I've read your template until the end).

---

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [x] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y` & `4.0.3`

</p>
</details>

---

**Comment by mikehardy** [comment] 2022-05-30 18:00
Hi there!
It's this:

```
:react-native-google-mobile-ads:android.compileSdk using custom value: 30
:react-native-google-mobile-ads:android.targetSdk using custom value: 30
```

As clearly indicated by this chunk:

```
[stderr]    > The minCompileSdk (31) specified in a
```

30 != 31

None of the maintainers here use Expo, so we're not best set up to support Expo users, we need help from the community for other Expo folks to have a good experience. That's cool that there will be a lot of Expo people showing up but it's still an open source repository and for it to be healthy we need help from everyone, right?

Adding anything that seems sensible here: https://github.com/invertase/react-native-google-mobile-ads/blob/main/docs/index.mdx#setting-up-google-admob - in the form of a PR would be most welcome.

I think to get access to android API31 (aka Android 12) you'll need:
- https://docs.expo.dev/build-reference/infrastructure/#image--ubuntu-2004-jdk-11-ndk-r21e--alias--latest (for Java11, a transitive dependency of Android API 31)
- specify the android 31 APIs here I think? https://docs.expo.dev/versions/latest/sdk/build-properties/#example-appjson-with-config-plugin

Once you are certain you have your app configured for Android API 31 and Java 11, this should build fine

*Assuming* it works (I hope it does?) Please please :pray: hit the edit button on the docs page and add an Expo note, and future users will have an easier time. Thanks!

**Comment by allandiego** [comment] 2022-05-31 17:07
@DoneDeal0 what version of expo are you using? I was able to build expo dev client without errors using sdk 45 since it uses android api 31 by default, to use a diferent expo version you need set android api version with custom EAS configuration using 

```ts
@expo/config-plugin
```

But im still facing some error with ads that I cant't identify because the app closes immediately after startup without any message. I think i'll have to attach android studio logcat to debug

**Comment by mikehardy** [comment] 2022-05-31 17:12
If it closes immediately that usually indicates that google mobile ads sdk did not find your admob id, I would closely examine the app.json to make sure the json property is named correctly etc, I believe you may examine the combined AndroidManifest.xml in AndroidStudio (or examine it from dissecting the built APK either by unzipping or by opening the APK in Android Studio to make sure it was interpolated

that interpolation happens like so during android build:

https://github.com/invertase/react-native-google-mobile-ads/blob/d4ed8ede312ca90886be182516de33525267b939/android/build.gradle#L54-L75

into placeholders here:

https://github.com/invertase/react-native-google-mobile-ads/blob/d4ed8ede312ca90886be182516de33525267b939/android/src/main/AndroidManifest.xml#L9-L16

and they should be visible (and correct, hopefully) in the merged manifest

`adb logcat` to just see the crash directly will provide the exact evidence of root cause though of course

**Closed** 2022-06-01 21:19 UTC
Labels: help wanted

**Comment by VictorioMolina** [comment] 2022-06-21 11:42
> add your adMob credential in app.json (out of the expo object)

Did you skip this [field](https://docs.expo.dev/versions/latest/config/app/#googlemobileadsappid)?


Currently, I was using this config, because, as mentioned in the Expo's `app.json` documentation, we should set `googleMobileAdsAppId` inside the iOS config.

export default ({ config }) => {
  const dynamicConfig = {
    "expo": {
      ios: {
        config: {
          googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY,
          googleMobileAdsAppId: process.env.ADMOB_IOS_APP_ID,  <-------
        },
      },
      ...
    },
    "react-native-google-mobile-ads": {
      android_app_id: process.env.ADMOB_ANDROID_APP_ID,
      ios_app_id: process.env.ADMOB_IOS_APP_ID, <-------
    },
  };

  dynamicConfig.expo = _.merge(config, dynamicConfig.expo);

  return dynamicConfig;
};

Have u tried submitting to app store without that field? Everything ok?

**Comment by mikehardy** [comment] 2022-06-21 12:31
@VictorioMolina I do not see how an expo-specific field would have bearing in a non-Expo module.

I believe you will need to follow our app install instructions here for our module.

I would expect your app.json to look very similar to our example app with regard to where config keys are in the JSON structure and what they are called etc 

https://github.com/invertase/react-native-google-mobile-ads/blob/5d2048b530b798740c9fed392772568f909dd6b2/RNGoogleMobileAdsExample/app.json#L1-L10

**Comment by VictorioMolina** [comment] 2022-06-21 12:49
@mikehardy yeah, you are right, I was asking just to make sure these fields were not used in the EAS build process or something like that. BTW, as far as I know, we can combine both app.json (static fields) and app.config.js (dynamic and environment fields) in Expo, and both configs are merged when building the binaries. But yes, it has no sense to use `googleMobileAdsAppId` as it is related to the deprecated `expo-ads-admob` (seems this Expo doc is out-to-date)

**Comment by mikehardy** [comment] 2022-09-14 21:06
Are these steps https://github.com/invertase/react-native-google-mobile-ads/issues/155#issuecomment-1142490214 (:point_up: ) still the right ones for Expo? It occurs to me (in the form of an Expo user who is confused on how to set this up) that we still don't have a section in the docs on Expo. Could someone with Expo experience / successfully using this module please post a PR to the docs? Your fellow Expo users will for sure grant you all their internet points for the day if you lend a hand :-)
