### ISSUE TITLE
Reward Ads not showing,

### ISSUE THREAD

**Issue by chzappsinc** [invertase/react-native-google-mobile-ads#135] opened 2022-05-08 23:03 UTC
## Issue

Possible Unhandled Promise Rejection (id: 4):
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.

Unable to load Reward ads, banner ads and others are working fine

Is this a bug or mistake from the side???

Platform: Android
Version: 6.2.1

```js
const rewarded = RewardedAd.createForAdRequest(TestIds.REWARDED);

  useEffect(() => {
    const unsubscribeLoaded = rewarded.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {
        setAdsLoaded(true);
        console.log('val');
      },
    );
    const unsubscribeEarned = rewarded.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {
        checkSlot();
      },
    );
    rewarded.load();
    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };
  }, []);

  if (!adsLoaded) {
    rewarded.load();
  }

---
```

app.json
```json
{
  "name": "XXXX",
  "displayName": "XXXX",
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-XXXX~6978380233",
    "ios_app_id": "ca-app-pub-XXXXX~6978380233"
  }
}
```

**Comment by mikehardy** [comment] 2022-05-08 23:14
Hi there! This may be a duplicate of this #109 - but honestly is so short on details I've got no idea. You didn't even change the default bug title 😆 - I have a hard time understanding the behavior, obviously

https://stackoverflow.com/help/how-to-ask

**Comment by chzappsinc** [comment] 2022-05-08 23:15
Sorry its 4:45 Am here am a little sleepy

**Comment by mikehardy** [comment] 2022-05-08 23:17
No worries, take your time, but please - any issue you log in an open source repo is a request for help. Make a good impression by taking your time, doing the work, and making it a *good* request for help

**Comment by chzappsinc** [comment] 2022-05-08 23:21
Hey, @mikehardy  Can you help me that the reward ad is not showing, Look at the code above
when I call rewards.show()
its showing an error 

``` js
Possible Unhandled Promise Rejection (id: 15):
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.

**Comment by mikehardy** [comment] 2022-05-08 23:50
Did you check the possibly duplicate issue number I linked? I have seen this on iOS but not on android, on android it works fine for me. On iOS, at least for the example app, I see the same thing and the google ads forum administrators (their support channel) indicates they cannot reproduce, so we may have a bug here. But you don't say anything about your versions or your execution environment so I'm not sure.

If it is on iOS then the symptom I see is that I actually see what appears to be an "advertisement sized amount of data" (vague: but trust me) yet it still says no fill. Why? Unsure.

Have you tried implementing the ad inspector feature ? (check our API, you'll see it, a recent feature addition). When I use that on iOS it says we no-fill and that's that as far as I know. We have a troubleshooting section for no-fills also, in the docs, you might examine it.

Other than that, I'm not sure what to offer. Perhaps one of the other maintainers here has more experience with rewarded ads and has specifically seen them work on iOS live, using this module and can confirm the module at least works for them.

**Comment by chzappsinc** [comment] 2022-05-09 00:00
#Updated

**Comment by mikehardy** [comment] 2022-05-09 02:01
Hmm - if it is android, I can't explain it as a failure. Our example app (check it out and run it!) works fine. Troubleshooting doc on no fills and/or ad inspector new feature may help you

**Comment by chzappsinc** [comment] 2022-05-09 08:37
` android rewarded ad event: rewarded_loaded
 LOG  android reward: {"amount":10,"type":"coins"})
 WARN  Possible Unhandled Promise Rejection (id: 1):
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.
Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown.`

This is what showing while clicking a button,
RN version: 0.68

**Comment by chzappsinc** [comment] 2022-05-09 08:42
@mikehardy am using hermes,
is this supportable?

`Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes`

**Comment by chzappsinc** [comment] 2022-05-09 10:01
Ads showing sometimes, Sometimes its thow error even after ads loaded

**Comment by wjaykim** [comment] 2022-05-09 10:08
Make sure you're not loading ad multiple times. Loading ad more than once could be happen because of state update, or many reasons, and it could be the reason of this.

**Comment by chzappsinc** [comment] 2022-05-09 10:13
```js
useEffect(() => {
    rewarded.load();
    const unsubscribeLoaded = rewarded.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {
        setAdsLoaded(true);
      },
    );
    const unsubscribeEarned = rewarded.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {
       
      },
    );
    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };
  }, []);
```

**Comment by wjaykim** [comment] 2022-05-09 10:15
Check these lines:

```
if (!adsLoaded) {
  rewarded.load();
}
```

**Comment by chzappsinc** [comment] 2022-05-09 10:17
@wjaykim Tried, Same error. I think ads are downloading, Internet Speed meter is showing 2MB/s while loading screen

**Comment by chzappsinc** [comment] 2022-05-09 10:20
```cli
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
```

**Comment by chzappsinc** [comment] 2022-05-09 10:22
rewarded. loaded not returning correct boolean 
its shows false even ads loaded and ads shown

**Comment by chzappsinc** [comment] 2022-05-09 10:29
```js
  const adUnitId = admob.reward_free_tournament;

  const rewarded = RewardedAd.createForAdRequest(adUnitId);

  useEffect(() => {
    rewarded.load();
    const unsubscribeLoaded = rewarded.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {
        setAdsLoaded(true);
        console.log('Ads Loaded Successfully');
      },
    );
    const unsubscribeEarned = rewarded.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {
        Toast.show('You can now join');
        nav.goBack();
      },
    );

    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };
  }, []);

  if (!adsLoaded) {
    rewarded.load();
  }
```

Log : 
```log
 LOG  Ads Loaded Successfully
 ERROR  Error: RewardedAd.show() The requested RewardedAd has not loaded and could not be shown., js engine: hermes
```

**Comment by wjaykim** [comment] 2022-05-09 10:32
Did you declared rewardedAd constant inside the component?

**Comment by chzappsinc** [comment] 2022-05-09 10:35
> Did you declared rewardedAd constant inside the component?

Didn't get you

**Comment by wjaykim** [comment] 2022-05-09 10:37
Where is this line located:

```js
const rewarded = RewardedAd.createForAdRequest(adUnitId);
```

It should be located outside of component block.

**Comment by chzappsinc** [comment] 2022-05-09 10:37
while commenting AddEventListner its working, But rewarded.loaded is not giving a right boolean always returning flase

```
// const unsubscribeLoaded = rewarded.addAdEventListener(
    //   RewardedAdEventType.LOADED,
    //   () => {
    //     setAdsLoaded(true);
    //     console.log('Ads Loaded Successfully');
    //   },
    // );
```

**Comment by chzappsinc** [comment] 2022-05-09 10:38
> Where is this line located:
> 
> ```js
> const rewarded = RewardedAd.createForAdRequest(adUnitId);
> ```
> 
> It should be located outside of component block.

Outside of useEffect

**Comment by wjaykim** [comment] 2022-05-09 10:42
Something like this:

```js
const rewarded = RewardedAd.createForAdRequest(adUnitId);

function Component() {

  useEffect(() => {
    rewarded.load();
    const unsubscribeLoaded = rewarded.addAdEventListener(
      RewardedAdEventType.LOADED,
      () => {
        setAdsLoaded(true);
        console.log('Ads Loaded Successfully');
      },
    );
    const unsubscribeEarned = rewarded.addAdEventListener(
      RewardedAdEventType.EARNED_REWARD,
      reward => {
        Toast.show('You can now join');
        nav.goBack();
      },
    );

    return () => {
      unsubscribeLoaded();
      unsubscribeEarned();
    };
  }, []);

  return (
    //...
  )
}
```

**Closed** 2022-05-09 10:54 UTC
Labels: help wanted

**Comment by wjaykim** [comment] 2022-05-09 11:07
@chzappsinc Did you resolved the problem?

**Comment by chzappsinc** [comment] 2022-05-09 11:08
@wjaykim Yes Thanks!

**Comment by dprajapati1179** [comment] 2023-04-27 12:51
Anyone can please share the code for showing multiple ads with the click of a button
I am having the same issue first ad lodes perfectly but other ads not loading and while calling shows my app is crashing
