### ISSUE TITLE
[🐛] App crashes continuously

### ISSUE THREAD

**Issue by Ivandeclei** [invertase/react-native-google-mobile-ads#89] opened 2022-03-12 23:46 UTC
## Issue

hello guys, after installing the library "invertase
/react-native-google-mobile-ads"

my application build successfully and the message appears.

"App crashes continuously"

and does not open the application.

build.gradle settings
kotlinVersion = "1.5.30"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        androidXAnnotation = "1.1.0"
        androidXBrowser = "1.0.0"

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
# N/A
```

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment] 2022-03-13 16:01
Sounds like you have an android crash issue.
You should run `adb logcat` in a Terminal while your machine is connected to the device and reproducing the crash, and you will see the error message.
I'm going to close this as not reproducible because the example app works for me, I cannot reproduce a crash.
You can try it yourself: https://github.com/invertase/react-native-google-mobile-ads/tree/main/example

**Closed by mikehardy** 2022-03-13 16:01 UTC
Labels: help wanted
