### ISSUE TITLE
[📚] Documentation broken links

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-google-mobile-ads#90] opened 2022-03-13 23:31 UTC
## Documentation Feedback

:point_down: all links in the main text in these screenshot are broken (lead to 404 page): BannerAd, BannerAdSize, RequestOptions.
![image](https://user-images.githubusercontent.com/20144632/158083942-85ce258c-b4ec-42dd-b05e-698e972a3f77.png)

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by dylancom** [comment] 2022-03-14 10:07
Related to #83

**Comment by mikehardy** [comment] 2022-03-14 14:10
Yep, docs.page just doesn't have the feature yet unfortunately, this is understandably frustrating

**Comment by mikehardy** [comment] 2022-04-18 15:27
I'm going to close this but the issue is not fixed, just that #83 is where we will track it. Note that there is progress here - docs.page should support refs to typedoc shortly

**Closed by mikehardy** 2022-04-18 15:27 UTC
Labels: help wanted
