### ISSUE TITLE
🔥 [🐛] The provided view controller is already presenting another view controller

### ISSUE THREAD

**Issue by Bartozzz** [invertase/react-native-google-mobile-ads#133] opened 2022-05-06 12:01 UTC
## Issue

Related to https://github.com/invertase/react-native-google-mobile-ads/issues/47. 

**Context:**
I am a hobbyist game developer making games w/ Expo. [`expo-ads-admob`](https://docs.expo.dev/versions/v45.0.0/sdk/admob/) will get deprecated in SDK 46 and the official documentation encourages to use `react-native-google-mobile-ads` instead:

> Deprecated. This module will be removed in SDK 46. There will be no replacement that works with the classic build service (expo build) because [the classic build service has been superseded by EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60). With EAS Build and [Development Builds](https://docs.expo.dev/development/introduction/), you should use [react-native-google-mobile-ads](https://github.com/invertase/react-native-google-mobile-ads) instead.

**Problem:**
Interstitial and Rewarded Ads cannot be shown inside modals (including `react-navigation` stacks rendered with `screenOptions={{ presentation: "modal" }}`). Trying to show an advertisement inside a modal results in the following error:

```
The provided view controller is already presenting another view controller
```

Are there plans to fix this? Are there any workarounds that do not require big refactors? Note that it was working without any issues in `expo-ads-admob`. Displaying ads on-top of modals is a popular practice in game development, for example when showing a _"You won"_ modal at the end of a level.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@react-navigation/elements": "^1.3.3",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.6.2",
    "expo": "~44.0.0",
    "expo-asset": "~8.4.4",
    "expo-constants": "~13.0.0",
    "expo-device": "~4.1.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-google-mobile-ads": "^6.2.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "react-test-renderer": "17.0.1",
    "typescript": "~4.3.5"
  },
  "resolutions": {
    "@types/react": "~17.0.21"
  }
}

```

#### `admob.json`:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'

require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'Game' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  # end

  post_install do |installer|
    react_native_post_install(installer)

    # Workaround `Cycle inside FBReactNativeSpec` error for react-native 0.64
    # Reference: https://github.com/software-mansion/react-native-screens/issues/842#issuecomment-812543933
    installer.pods_project.targets.each do |target|
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
  System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 518.58 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.7.0 - ~/Projekty/Games/Game/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.7.0 - ~/Projekty/Games/Game/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **Are you using `TypeScript`?**
  - `~4.3.5`

</p>
</details>

**Comment by mikehardy** [comment] 2022-05-06 13:50
Hey there :wave: - that's news to me re: expo pointing folks here, and this bug in particular - you are the first reporter
As such, there are no plans to fix it currently but it's a use case that seems reasonable to support

I would welcome any investigation + fix in this area, and as a use case it seems pretty simple to add to the example App.tsx file so that the failure may be easily reproduced, and in my experience it's usually a pretty rapid fix after that. The code here isn't too complicated really. If there is some reference implementation that works already (there is - the expo module) that typically works for inspiration as well

If you post a PR we can collaborate and I/we can get it merged released really quickly

**Comment by dylancom** [comment] 2022-05-06 14:06
Our code: `[interstitial presentFromRootViewController:RCTSharedApplication().delegate.window.rootViewController];`
Expo Ads AdMob: `[self->_interstitial presentFromRootViewController:self.utilities.currentViewController];`

I guess we have to investigate what Expo Ads Admob does differently at: https://github.com/expo/expo/blob/master/packages/expo-ads-admob/ios/EXAdsAdMob/EXAdsAdMobInterstitial.m#L103

**Comment by mikehardy** [comment] 2022-05-06 14:23
Looks like @hannojg has a tested chunk of code here in this comment on related discussion in https://github.com/invertase/react-native-google-mobile-ads/pull/51#issuecomment-1024957196

**Comment by wjaykim** [comment] 2022-05-06 15:02
Yes, the problem is our code is not getting the topmost View Controller.

**Comment by Bartozzz** [comment] 2022-05-06 15:11
@dylancom it works! Thank you all folks for quick reaction, that's awesome!

<img width="564" alt="image" src="https://user-images.githubusercontent.com/6741707/167161259-023d25ac-33db-4ef2-82f4-46044e285d8c.png">

**Closed** 2022-05-06 15:26 UTC
Labels: help wanted
